---
codecov:
  require_ci_to_pass: false

coverage:
  range: 25..75

  status:
    project:
      default:
        target: auto
        threshold: 1%
        if_ci_failed: success
    patch: off

comment: false
