---
kind: pipeline
type: kubernetes
name: default

services:
  - name: docker
    image: docker:20.10-dind
    entrypoint: [dockerd]
    privileged: true
    volumes:
      - name: docker-socket
        path: /var/run

steps:
  - name: setup-ci
    image: autonomy/build-container:latest
    commands:
      - setup-ci
    privileged: true
    volumes:
      - name: docker-socket
        path: /var/run
      - name: outerdockersock
        path: /var/outer-run
      - name: docker
        path: /root/.docker/buildx

  - name: build-pull-request
    image: autonomy/build-container:latest
    pull: always
    environment:
      PLATFORM: linux/amd64,linux/arm64
    commands:
      - make
    when:
      event:
        include:
          - pull_request
    volumes:
      - name: docker-socket
        path: /var/run
      - name: outerdockersock
        path: /var/outer-run
      - name: docker
        path: /root/.docker/buildx

  - name: test-pull-request
    image: autonomy/build-container:latest
    pull: always
    environment:
      PLATFORM: linux/amd64,linux/arm64
    commands:
      - make env-up
      - make test
    when:
      event:
        include:
          - pull_request
    volumes:
      - name: docker-socket
        path: /var/run
      - name: outerdockersock
        path: /var/outer-run
      - name: docker
        path: /root/.docker/buildx

  - name: build-and-publish
    image: autonomy/build-container:latest
    pull: always
    environment:
      GHCR_USERNAME:
        from_secret: ghcr_username
      GHCR_PASSWORD:
        from_secret: ghcr_token
      PLATFORM: linux/amd64,linux/arm64
    commands:
      - docker login --username "$${GHCR_USERNAME}" --password "$${GHCR_PASSWORD}" ghcr.io
      - make PUSH=true
    when:
      event:
        exclude:
          - pull_request
    volumes:
      - name: docker-socket
        path: /var/run
      - name: outerdockersock
        path: /var/outer-run
      - name: docker
        path: /root/.docker/buildx

  - name: build-release
    image: autonomy/build-container:latest
    pull: always
    commands:
      - make release
    when:
      event:
        - tag
    volumes:
      - name: docker-socket
        path: /var/run
      - name: outerdockersock
        path: /var/outer-run
      - name: docker
        path: /root/.docker/buildx

  - name: release
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      checksum:
        - sha256
        - sha512
      draft: true
      files:
        - _out/*
    when:
      event:
        - tag

volumes:
  - name: docker-socket
    temp: {}
  - name: outerdockersock
    host:
      path: /var/ci-docker
  - name: docker
    temp: {}
---
kind: pipeline
type: kubernetes
name: notify

clone:
  disable: true

steps:
  - name: slack
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook
      channel: proj-talos-maintainers
    when:
      status:
        - success
        - failure

trigger:
  status:
    - success
    - failure

depends_on:
  - default

---
kind: signature
hmac: 0e8710aa7032501fcad228e01d94233a8bbe70b432c232887c4ab9d4f55a707a

...
