# permissions to do viewer talosconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: talosconfig-viewer-role
rules:
- apiGroups:
  - bootstrap.cluster.x-k8s.io
  resources:
  - talosconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - bootstrap.cluster.x-k8s.io
  resources:
  - talosconfigs/status
  verbs:
  - get
